FROM python:3.8

WORKDIR /app

RUN apt-get update && apt-get install -y netcat

COPY ./Robos/Robo_01.py /app

COPY ./Scripts/autostart.sh /app

RUN chmod +x ./autostart.sh

RUN pip install pika

CMD ["./autostart.sh", "rabbitmq", "python", "./Robo_01.py"]