FROM python:3.8

ENV TZ=America/Sao_Paulo

WORKDIR /app

RUN apt-get update && apt-get install -y netcat

COPY ./Homebrokers/HB.py /app

COPY ./Scripts/autostart.sh /app

RUN chmod +x ./autostart.sh

RUN pip install pika