version: '3.1'
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - "5672:5672"
        - "15672:15672"
  bv:
    build:
      context: .
      dockerfile: /BolsaDeValores/Dockerfile_BV
    ports:
      - 5000:5000
    links:
      - rabbitmq

  hb:
    build:
      context: .
      dockerfile: /BolsaDeValores/Dockerfile_HB
    ports:
      - 6000:6000
    links:
      - rabbitmq
      - bv

  robo1:
    build:
      context: .
      dockerfile: /BolsaDeValores/Dockerfile_RB
    links:
      - rabbitmq
      - hb

  robo2:
    build:
      context: .
      dockerfile: /BolsaDeValores/Dockerfile_RB
    links:
      - rabbitmq
      - hb