version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./Configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      
  bv:
    build:
      context: .
      dockerfile: ./BolsaDeValores/Dockerfile_BV
    container_name: BolsadeValores
    restart: on-failure
    depends_on:
      - rabbitmq

  hb1:
    build:
      context: .
      dockerfile: ./Homebrokers/Dockerfile_HB
    container_name: HomeBroker01
    restart: on-failure
    command: ["./autostart.sh", "rabbitmq", "python", "./HB.py", "1"]
    depends_on:
      - bv

  hb2:
    build:
      context: .
      dockerfile: ./Homebrokers/Dockerfile_HB
    container_name: HomeBroker02
    restart: on-failure
    command: ["./autostart.sh", "rabbitmq", "python", "./HB.py", "2"]
    depends_on:
      - hb1

  robo1:
    build:
      context: .
      dockerfile: ./Robos/Dockerfile_RB
    container_name: RoboTrader01
    restart: on-failure
    command: ["./autostart.sh", "rabbitmq", "python", "./Robo.py", "1", "1"]
    depends_on:
      - hb2

  robo2:
    build:
      context: .
      dockerfile: ./Robos/Dockerfile_RB
    container_name: RoboTrader02
    restart: on-failure
    command: ["./autostart.sh", "rabbitmq", "python", "./Robo.py", "1", "2"]
    depends_on:
      - robo1

  robo3:
    build:
      context: .
      dockerfile: ./Robos/Dockerfile_RB
    container_name: RoboTrader03
    restart: on-failure
    command: ["./autostart.sh", "rabbitmq", "python", "./Robo.py", "2", "3"]
    depends_on:
      - robo2

  robo4:
    build:
      context: .
      dockerfile: ./Robos/Dockerfile_RB
    container_name: RoboTrader04
    restart: on-failure
    command: ["./autostart.sh", "rabbitmq", "python", "./Robo.py", "2", "4"]
    depends_on:
      - robo3

volumes:
  rabbitmq_data: