version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./Configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      
  bv:
    build:
      context: .
      dockerfile: ./BolsaDeValores/Dockerfile_BV
    container_name: BolsadeValores
    restart: on-failure
    depends_on:
      - rabbitmq

  hb:
    build:
      context: .
      dockerfile: ./Homebrokers/Dockerfile_HB
    container_name: HomeBroker01
    restart: on-failure
    command: ["./autostart.sh", "rabbitmq", "python", "./HB.py", "1"]
    depends_on:
      - bv

  robo:
    build:
      context: .
      dockerfile: ./Robos/Dockerfile_RB
    container_name: RoboTrader01
    restart: on-failure
    command: ["./autostart.sh", "rabbitmq", "python", "./Robo.py", "1"]
    depends_on:
      - hb
      - bv

volumes:
  rabbitmq_data: